# Load Libraries

In [26]:
import xml.etree.ElementTree as ET
import os

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import Ridge
from scipy.stats import pearsonr
from sklearn import preprocessing

import zipfile
from glob import glob

import seaborn as sns
from sympy import subsets
sns.set()

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

#import japanize_matplotlib
import unicodedata

from MyMasterClass import MyMasterClass

## Kanjya class

In [27]:
class MyKanjyaClass(MyMasterClass):

    def __init__(self, data_dir=u"L:\\Miyuki", output_dir = u"L:\\epson_pxm840f\\Shikakku"):
        super().__init__(data_dir, output_dir)


        filename = "KANJA_List.txt"
        self.filename = os.path.join(self.data_dir, filename)

    def readCSV(self):

        df = super().readCSV(self.filename)
        df = df.iloc[:,1:7].copy()

        newcols = ["id","kaiin","Kana","Name","birth","sex2"]

        df.drop_duplicates(inplace=True)
        df.columns = newcols
        df.drop(["kaiin"], inplace=True, axis=1)


        #print(df.shape)
        return df

In [28]:
kanjya = MyKanjyaClass()

In [29]:
df = kanjya.readCSV()

In [30]:
df

           id       Kana    Name       birth sex2
0    90003795   ｱｲﾀﾞ ﾏﾘｴ  会田　摩利恵  1959/12/25    女
1    90006902     ｱｷﾏ ｱｲ    秋間　愛  2010/08/26    女
2    90003103   ｱｷﾏ ﾌｼﾞｺ  秋間　不二子  1934/02/08    女
3    90002609    ｱｷﾏ ﾏｻｼ    秋間　政  1932/04/28    男
5    90009112   ｱｷﾓﾄ ﾏｻｺ   秋元　政子  1957/01/17    女
..        ...        ...     ...         ...  ...
628  90009147   ﾜｶﾂｷ ｱｷﾗ    若月　彰  1950/07/07    男
632  90007622   ﾜｶﾏﾂ ﾓﾄﾖ   若松　雅代  1940/07/15    女
634  90006220  ﾜﾀﾅﾍﾞ ﾅｵｺ   渡邉　直子  1971/08/18    女
640  90009021  ﾜﾀﾅﾍﾞ ﾊﾂﾐ   渡部　初美  1948/03/04    女
646  90009020   ﾜﾀﾉ ｼｹﾞﾙ    綿野　滋  1932/07/30    男

[294 rows x 5 columns]